import { createOrder } from "../domain/order";
import type { Product, Store, Voucher } from "../domain/types";

export const products: Product[] = [
  {
    id: "c1",
    name: "Kopi Susu Mekar",
    category: "Coffee",
    price: 24000,
    image: "/kopi-susu.jpg",
    available: true,
    popular: true,
    description:
      "Espresso, susu segar, dan manisnya gula aren. Favorit untuk setiap hari.",
  },
  {
    id: "c2",
    name: "Caffè Latte",
    category: "Coffee",
    price: 28000,
    image: "/latte.jpg",
    available: true,
    popular: true,
    description: "Double espresso dengan susu yang lembut dan seimbang.",
  },
  {
    id: "c3",
    name: "Americano",
    category: "Coffee",
    price: 22000,
    image: "/americano.jpg",
    available: true,
    description: "Espresso pilihan dengan karakter bold dan clean finish.",
  },
  {
    id: "c4",
    name: "Cappuccino",
    category: "Coffee",
    price: 28000,
    image: "/cappuccino.jpg",
    available: true,
    description: "Perpaduan klasik espresso, susu, dan milk foam yang tebal.",
  },
  {
    id: "c5",
    name: "Caramel Macchiato",
    category: "Coffee",
    price: 32000,
    image: "/kopi-susu.jpg",
    available: true,
    description: "Espresso dan susu dengan sentuhan saus karamel.",
  },
  {
    id: "c6",
    name: "Mocha",
    category: "Coffee",
    price: 32000,
    image: "/latte.jpg",
    available: true,
    description: "Cokelat, espresso, dan susu dalam satu cangkir yang hangat.",
  },
  {
    id: "n1",
    name: "Matcha Latte",
    category: "Tea",
    price: 30000,
    image: "/matcha.jpg",
    available: true,
    popular: true,
    description: "Matcha Jepang dengan susu segar, earthy dan creamy.",
  },
  {
    id: "n2",
    name: "Chocolate",
    category: "Tea",
    price: 28000,
    image: "/chocolate.jpg",
    available: true,
    description: "Cokelat pekat dengan susu segar yang creamy.",
  },
  {
    id: "n3",
    name: "Lemon Tea",
    category: "Tea",
    price: 22000,
    image: "/lemon-tea.jpg",
    available: true,
    description: "Teh pilihan dengan lemon segar, ringan dan menyegarkan.",
  },
  {
    id: "p1",
    name: "Butter Croissant",
    category: "Pastry & Bites",
    price: 25000,
    image: "/croissant.jpg",
    available: true,
    description: "Croissant berlapis, renyah di luar dan lembut di dalam.",
  },
  {
    id: "p2",
    name: "Pain au Chocolat",
    category: "Pastry & Bites",
    price: 28000,
    image: "/pastry.jpg",
    available: true,
    description: "Pastry mentega dengan isian dark chocolate.",
  },
  {
    id: "p3",
    name: "Cinnamon Roll",
    category: "Pastry & Bites",
    price: 26000,
    image: "/cinnamon.jpg",
    available: false,
    description: "Roti kayu manis lembut dengan cream cheese glaze.",
  },
  {
    id: "r1",
    name: "Beef Teriyaki Ricebowl",
    category: "Ricebowl",
    price: 42000,
    image: "/ricebowl.jpg",
    available: true,
    popular: true,
    description: "Nasi hangat dengan beef teriyaki, telur, dan sayuran segar.",
  },
  {
    id: "r2",
    name: "Chicken Sambal Ricebowl",
    category: "Ricebowl",
    price: 36000,
    image: "/ricebowl.jpg",
    available: true,
    description: "Ayam panggang dengan sambal matah dan nasi hangat.",
  },
  {
    id: "no1",
    name: "Mie Goreng Jawa",
    category: "Noodle",
    price: 34000,
    image: "/noodle.jpg",
    available: true,
    popular: true,
    description: "Mie goreng dengan sayuran, telur, dan bumbu khas Jawa.",
  },
  {
    id: "no2",
    name: "Creamy Chicken Noodle",
    category: "Noodle",
    price: 38000,
    image: "/noodle.jpg",
    available: true,
    description: "Mie lembut dengan ayam dan saus creamy yang gurih.",
  },
];
export const vouchers: Voucher[] = [
  {
    code: "MEKAR10",
    type: "percent",
    value: 10,
    minimum: 50000,
    expires: "2030-12-31",
    active: true,
    label: "Diskon 10%",
    description: "Min. belanja Rp50.000",
  },
  {
    code: "KOPIHEMAT",
    type: "fixed",
    value: 10000,
    minimum: 75000,
    expires: "2030-12-31",
    active: true,
    label: "Potongan Rp10.000",
    description: "Min. belanja Rp75.000",
  },
  {
    code: "LAMA2025",
    type: "percent",
    value: 20,
    minimum: 0,
    expires: "2025-12-31",
    active: true,
    label: "Voucher kedaluwarsa",
    description: "Contoh validasi",
  },
  {
    code: "NONAKTIF",
    type: "fixed",
    value: 5000,
    minimum: 0,
    expires: "2030-12-31",
    active: false,
    label: "Voucher tidak aktif",
    description: "Contoh validasi",
  },
];
export function createDemoStore(now: Date, createId: () => string): Store {
  const start = now.toISOString();
  return {
    version: 1,
    session: { name: "Alya Putri", loginAt: start },
    shift: { id: createId(), cashier: "Alya Putri", start, opening: 300000 },
    shifts: [],
    order: createOrder(createId()),
    held: [],
    transactions: [],
    settings: {
      receiptPrinter: true,
      kitchenPrinter: true,
      drawer: true,
      tax: 10,
      service: 5,
      networkFailure: false,
      paymentFailure: false,
      printerFailure: false,
    },
  };
}
